# Page settings

baseURL = "https://musical-monstera-aed8e0.netlify.app/"
languageCode = "en"
title = "Brian Chappell Professional Experience"
enableGitInfo = true
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Brian Chappell"
    description = "Brians Resume"
    og_image = "Brian-Head-shot.png"
    twitterName = "@brianchappell"
    ghRepo = "https://github.com/greentechgear/resume/"
    hugoRepo = "https://github.com/gohugoio/hugo/"

    [params.profile]
        enable = true 
        name = "Brian Chappell"
        tagline = "Professional Experience"
        avatar = "Brian-Head-shot.png"

    [params.contact]
        enable = true

        location = "Raleigh, NC, USA"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:"
        text = "See email"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:brianc@brianchappell.com"
        text = "brianc@brianchappell.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://brianchappell.com"
        text = "Blog"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "B2B"
        [[params.skills.list]]
        title = "SaaS"
        [[params.skills.list]]
        title = "Ecommerce"
        [[params.skills.list]]
        title = "Search Marketing"
        [[params.skills.list]]
        title = "Wordpress, googleAnalytics, GAds, Bing & LinkedIn Ads"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS"
        university = "Virginia Tech"
        dates = "2000-2005 (yes, the Michael Vick era)"


    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Professional Business Seller™ I"
        body = "AdaptPartners.com"
        date = "2016"

        [[params.awards.list]]
        name = "Professional Business Seller™ II"
        body = "AdaptMarketing.com"
        date = "2022"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Chappellisms"
        level = "Fluent"

        [[params.languages.list]]
        name = "English"
        level = "Fluent"

        [[params.languages.list]]
        name = "Marketing-Dev speak"
        level = "Fluent"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Horses"
        [[params.interests.list]]
        name = "Costa Rica"
        [[params.interests.list]]
        name = "Fungi"
        [[params.interests.list]]
        name = "Bugs"
        [[params.interests.list]]
        name = "Trees"


    [params.summary]
        enable = true
        text = "Full Stack Marketer and Product Developer."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Community Founder"
        dates = "2025 - Present"
        company = "Consultdex.com"
        details = "Founded and building a intiment consultant community platform featuring specialized categories for critiques, business ideas, software guides, and professional development. Created a space for consultants to share knowledge, analyze campaigns, and collaborate on innovative projects."
        [[params.experience.list.items]]
        details = "Built comprehensive community platform with categories: Consult & Critique, Steal This Idea, Software Guides, Mind & Business, and AMA sessions"
        [[params.experience.list.items]]
        details = "Facilitated knowledge sharing across web performance, content quality, accessibility, data analytics, branding, and paid media"
        [[params.experience.list.items]]
        details = "Created space for consultants to share innovative business ideas and software mastery guides"
        [[params.experience.list.items]]
        details = "Platform: https://consultdex.com/"

        [[params.experience.list]]
        title = "Product Developer"
        dates = "2025 - Present"
        company = "Calenlist.com"
        details = "Developed a calendar sharing and monetization platform that allows creators, coaches, and community leaders to share their calendars and build revenue through subscription models. Built with Google Calendar integration and simple monetization features."
        [[params.experience.list.items]]
        details = "Created platform for calendar sharing and community building with Google Calendar integration"
        [[params.experience.list.items]]
        details = "Implemented subscription-based monetization model for calendar creators and community leaders"
        [[params.experience.list.items]]
        details = "Built templates for Office Hours, Community Events, Webinar Series, Consulting Sessions, Fitness Classes, and Workshop Series"
        [[params.experience.list.items]]
        details = "Platform: https://calenlist.com/"

        [[params.experience.list]]
        title = "Founder"
        dates = "2024 - Present"
        company = "Medvertise"
        details = "Transform Medical Equipment Sales with the Medvertise Network. Medvertise simplifies the way you find, price, and sell equipment, saving you time and increasing your margins. Built by experts in the medical equipment industry from the team that created the world's largest medical imaging aftermarket company, Probo Medical."
        [[params.experience.list.items]]
        details = "AI-powered platform for medical equipment sales with real-time market insights and pricing data"
        [[params.experience.list.items]]
        details = "Average time saved: 8+ hours/week, Margin increase: +23% on average"
        [[params.experience.list.items]]
        details = "Exclusive access to both aftermarket pricing and new OEM products"
        [[params.experience.list.items]]
        details = "Auto-updated listings synchronized across all major platforms (Google, Bing, etc.)"
        [[params.experience.list.items]]
        details = "AI Chatbot assistance and integrated platform listings for 5x faster management"

        [[params.experience.list]]
        title = "Founder"
        dates = "2023 - Present"
        company = "Rival Track Inc."
        details = "Rival Track is run day to day by Brian Chappell and serves as his mode for competitive insights and informative takes on web competition and other marketing and communication tactics your competitors might be engaging in."
        [[params.experience.list.items]]
        details = "Competitive Monitoring as a service"
        [[params.experience.list.items]]
        details = "Website: https://rivaltrack.com/"

        [[params.experience.list]]
        title = "Founder"
        dates = "2019 - Present"
        company = "Promote Device"
        details = "Promote Device specializes in building a strategic marketing presence tailored to individual businesses within the industrial and healthcare verticals. Specialties include search engine optimization (SEO), Google Ads, Google Merchant Center, Google Retail, Bing Adcenter, Amazon Business, as well as general Content Management and Lead Management Customer Service."
        [[params.experience.list.items]]
        details = "Lead Generation Company for Industrial and Healthcare Companies"
        [[params.experience.list.items]]
        details = "Located in RTP NC Area"

        [[params.experience.list]]
        title = "Founder"
        dates = "2016 - Present"
        company = "PromoteMed Inc."
        details = "PromoteMed focuses on growing patient bases for Aesthetic practices through to Veterinarians and everything in between. We utilize integrated digital marketing techniques to drive success for our healthcare partners."
        [[params.experience.list.items]]
        details = "Digital Marketing Agency for the Healthcare Industry"
        [[params.experience.list.items]]
        details = "Located in Cary, NC"

        [[params.experience.list]]
        title = "Owner / Lead Strategist"
        dates = "2008 - 2022"
        company = "AdaptMarketing.com"
        details = "Managed and led digital marketing agency for over 10 years and 50+ clients. Managed team of 12. Acquired by CopyPress in 2022."
        [[params.experience.list.items]]
        details = "Developed link and content promotion tools."

        [[params.experience.list]]
        title = "Director of Marketing"
        dates = "2005 - 2008"
        company = "GoTickets.com"
        details = "Competitive 2ndary Ticket Broker competing against the largest Ticket Brokers in the USA. Topping out at #3 in 2008. Acquired by Pfingstein Partners."
        [[params.experience.list.items]]
        details = "Created initial link system to monitor link efforts as part of GoTickets.com"

        [[params.experience.list]]
        title = "Medical Equipment Business Development"
        dates = "2008 - 2019"
        company = "Providian Medical"
        details = "Led business development initiatives in the medical imaging equipment market, contributing to significant market consolidation and company growth."
        [[params.experience.list.items]]
        details = "Sold for 6x EBITA"
        [[params.experience.list.items]]
        details = "Created an online lead generation system extending across the market allowing for Generated quotes on 100million in ultrasound equipment"
        [[params.experience.list.items]]
        details = "Assisted the transition and consolidation of the Imaging market which in turn created a 500 million entity in ProboMedical"

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "BullionMax"
        meta = "Financial project"
        url = "https://bullionmax.com"
        tagline = "Managed the Inventory / Content / Search for a Gold/Silver dealer launch"
        
        [[params.projects.list]]
        title = "BitIRA"
        meta = "Financial project"
        url = "https://bitira.com"
        tagline = "Cryptocurrency IRA investment product"

        [[params.projects.list]]
        title = "Promote Device"
        meta = "Healthcare project"
        url = "https://promotedevice.com"
        tagline = "Healthcare lead generation company"

        [[params.projects.list]]
        title = "Buildium"
        meta = "SaaS project"
        url = "https://buildium.com"
        tagline = "Property management software"

        [[params.projects.list]]
        title = "Raven Tools"
        meta = "SaaS project"
        url = "https://raventools.com"
        tagline = "SEO tools"

        [[params.projects.list]]
        title = "Ignite Social Media"
        meta = "Services project"
        url = "https://ignitesocialmedia.com"
        tagline = "Social media agency"


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "horses, costa rica, fungi, bugs, trees, 3d printing, linux, automations"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://consultdex.com/profile/brian-chappell/"
        title = "/brian-chappell"
        [[params.social.list]]
        icon = "fab fa-mastodon"
        url = "https://mas.to/@brianchappell"
        title = "@brianchappell"
        
