# Page settings

baseURL = "https://musical-monstera-aed8e0.netlify.app/"
languageCode = "en"
title = "Brian Chappell Professsional Experience"
enableGitInfo = true
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Brian Chappell"
    description = "Brians Resume"
    og_image = "Brian-Head-shot.png"
    twitterName = "@brianchappell"
    ghRepo = "https://github.com/greentechgear/resume/"
    hugoRepo = "https://github.com/gohugoio/hugo/"

    [params.profile]
        enable = true 
        name = "Brian Chappell"
        tagline = "Resume"
        avatar = "Brian-Head-shot.png"

    [params.contact]
        enable = true

        location = "Raleigh, NC, USA"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:"
        text = "See email"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:brianc@brianchappell.com"
        text = "brianc@brianchappell.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://brianchappell.com"
        text = "Blog"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "B2B"
        [[params.skills.list]]
        title = "SaaS"
        [[params.skills.list]]
        title = "Ecommerce"
        [[params.skills.list]]
        title = "Search Marketing"
        [[params.skills.list]]
        title = "Wordpress, GA, GAds, FB Ads, LinkedIn Ads"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS"
        university = "Virginia Tech"
        dates = "2000-2005 (yes, the Michael Vick era)"


    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Professional Business Seller™ I"
        body = "AdaptPartners.com"
        date = "2016"

        [[params.awards.list]]
        name = "Professional Business Seller™ II"
        body = "AdaptMarketing.com"
        date = "2022"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Chappellisms"
        level = "Fluent"

        [[params.languages.list]]
        name = "English"
        level = "Fluent"

        [[params.languages.list]]
        name = "Marketing-Dev speak"
        level = "Fluent"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Horses"
        [[params.interests.list]]
        name = "Costa Rica"
        [[params.interests.list]]
        name = "Fungi"
        [[params.interests.list]]
        name = "Bugs"
        [[params.interests.list]]
        name = "Trees"


    [params.summary]
        enable = true
        text = "Full Stack Marketer and Product Developer."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Director of Marketing"
        dates = "2005 - 2008"
        company = "GoTickets.com"
        details = "Competitve 2ndary Ticket Broker competing against the largest Ticket Brokers in the USA. Topping out at #3 in 2008. Aquired by Pfigstein Partners."
        [[params.experience.list.items]]
        details = "Created initial link system to monitor link efforts as part of GoTickets.com"

        [[params.experience.list]]
        title = "Owner / Lead Strategist"
        dates = "2008 - 2022"
        company = "AdaptMarketing.com"
        details = "Managed and led digital marketing agency for over 10 years and 50+ clients. Managed team of 12. Aquired by CopyPress in 2022."
        [[params.experience.list.items]]
        details = "Developed link and content promotion tools."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "BullionMax"
        meta = "Financial project"
        url = "https://bullionmax.com"
        tagline = "Managed the Inventory / Content / Search for a Gold/Silver dealer launch"
        
        [[params.projects.list]]
        title = "BitIRA"
        meta = "Financial project"
        url = "https://bitira.com"
        tagline = "Cryptocurrency IRA investment product"

        [[params.projects.list]]
        title = "Promote Device"
        meta = "Healthcare project"
        url = "https://promotedevice.com"
        tagline = "Healthcare lead generation company"

        [[params.projects.list]]
        title = "Buildium"
        meta = "SaaS project"
        url = "https://buildium.com"
        tagline = "Property management software"

        [[params.projects.list]]
        title = "Raven Tools"
        meta = "SaaS project"
        url = "https://raventools.com"
        tagline = "SEO tools"

        [[params.projects.list]]
        title = "Ignite Social Media"
        meta = "Services project"
        url = "https://ignitesocialmedia.com"
        tagline = "Social media agency"


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "horses, costa rica, fungi, bugs, trees"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://consultdex.com/profile/brian-chappell/"
        title = "/brian-chappell"
        [[params.social.list]]
        icon = "fab fa-mastodon"
        url = "https://mas.to/@brianchappell"
        title = "@brianchappell"
        
